SELECT 
            CaseID
            ,SAOCaseNumber
            ,OffenseDate
            ,ArrestDate
            ,ArrestingAgencyID
            ,ArrestingCaseNumber
            ,OBTSNumber
            ,CitationID
            ,StatuteID
            ,ChargePhase
            ,SetBondAmount
            ,InitialSequenceNumber
            ,InitialStatuteID
            ,InitialChargeStatus
            ,InitialDrugType
            ,InitialChargeWeapons
            ,InitialChargeRange
            ,InitialChargeAmount
            ,InitialChargeUnit
            ,InitialStatuteDescription
            ,InitialChargeLevel
            ,InitialChargeDegree
            ,InitialGeneralOffenseCharacter
            ,InitialOffenseActivity
            ,ProsecutorSequenceNumber
            ,ProsecutorStatuteID
            ,ProsecutorChargeStatus
            ,ProsecutorDrugType
            ,ProsecutorChargeWeapons
            ,ProsecutorChargeRange
            ,ProsecutorChargeAmount
            ,ProsecutorChargeUnit
            ,ProsecutorFileDate
            ,ProsecutorFinalDecisionDate
            ,ProsecutorFinalAction
            ,ProsecutorDefermentType
            ,ProsecutorDefermentDate
            ,ProsecutorStatuteDescription
            ,ProsecutorChargeLevel
            ,ProsecutorChargeDegree
            ,ProsecutorGeneralOffenseCharacter
            ,ProsecutorOffenseActivity
            ,CourtSequenceNumber
            ,CourtStatuteID
            ,CourtChargeStatus
            ,CourtDrugType
            ,CourtChargeWeapons
            ,CourtChargeRange
            ,CourtChargeAmount
            ,CourtChargeUnit
            ,CourtDecisionDate
            ,CourtActionTaken
            ,CourtFinalPlea
            ,CourtFinalPleaEnteredDate
            ,CourtStatuteDescription
            ,CourtChargeLevel
            ,CourtChargeDegree
            ,CourtGeneralOffenseCharacter
            ,CourtOffenseActivity
            ,ReOpenDate
            ,ReOpenReason
            ,ReOpenedChargeClosedDate
            ,AppealDate
            ,ArrestPartyNameID
            ,DispositionPartyNameID
            ,SentenceImposedDate
            ,SentenceEffectiveDate
            ,JudgeID
            ,JurisdictionRetained
            ,SentenceStatus
            ,SentenceStatusCaseNumber
            ,SentenceStatusChargeCount
            ,SentenceNotes
            ,CourtDocketNumber
            ,MinConfinementCode
            ,MaxConfinementCode
            ,MinConfinementYears
            ,MinConfinementMonths
            ,MinConfinementDays
            ,MaxConfinementYears
            ,MaxConfinementMonths
            ,MaxConfinementDays
            ,OBTSMinConfinementYears
            ,OBTSMinConfinementMonths
            ,OBTSMinConfinementDays
            ,OBTSMaxConfinementYears
            ,OBTSMaxConfinementMonths
            ,OBTSMaxConfinementDays
            ,ConfinementTypeCode
            ,SuspendConfinementYears
            ,SuspendConfinementMonths
            ,SuspendConfinementDays
            ,OBTSSuspendConfinementYears
            ,OBTSSuspendConfinementMonths
            ,OBTSSuspendConfinementDays
            ,CreditTimeServedCode
            ,CreditTimeServedYears
            ,CreditTimeServedMonths
            ,CreditTimeServedDays
            ,OBTSCreditTimeServedHours
            ,ProbationTypeCode
            ,ProbationLengthCode
            ,ProbationLengthYears
            ,ProbationLengthMonths
            ,ProbationLengthDays
            ,OBTSProbationLengthYears
            ,OBTSProbationLengthMonths
            ,OBTSProbationLengthDays
            ,CommunityControlYears
            ,CommunityControlMonths
            ,CommunityControlDays
            ,OBTSCommunityControlYears
            ,OBTSCommunityControlMonths
            ,OBTSCommunityControlDays
            ,DLActionCode
            ,LicenseSuspendedCode
            ,LicenseSuspendedYears
            ,LicenseSuspendedMonths
            ,LicenseSuspendedDays
            ,LicenseReceivedByCourt
            ,OBTSLicenseSuspendedYears
            ,OBTSLicenseSuspendedMonths
            ,OBTSLicenseSuspendedDays
            ,FineAmount
            ,CourtCostAmount
            ,RestitutionAmount
            ,SentenceProvision1
            ,SentenceProvision2
            ,SentenceProvision3
            ,SentenceProvision4
            ,SentenceProvision5
            ,SpecialSentenceProvision1
            ,SpecialSentenceProvision2
            ,SpecialSentenceProvision3
            ,SpecialSentenceProvision4
            ,SpecialSentenceProvision5
            ,SpecialSentenceProvision6
            ,SpecialSentenceProvision7
            ,DrugTraffickingTermYears
            ,DrugTraffickingTermMonths
            ,DrugTraffickingTermDays
            ,OBTSDrugTraffickingTermYears
            ,OBTSDrugTraffickingTermMonths
            ,OBTSDrugTraffickingTermDays
            ,CostOfSupervisionRate
            ,CountyOfSupervision
            ,CommunityServiceHours
            ,RestitutionID
            ,PlaintiffAttorneyID
            ,DefendantAttorneyID
            ,TrialType
            ,VerdictTypeCode
            ,AppearanceTypeCode
            ,DLRestrictedCode
            ,LicenseRestrictedCode
            ,LicenseRestrictedYears
            ,LicenseRestrictedMonths
            ,LicenseRestrictedDays
            ,OBTSLicenseRestrictedYears
            ,OBTSLicenseRestrictedMonths
            ,OBTSLicenseRestrictedDays
            ,FailureTermDays
            ,FailureTermCreditTimeServed
            ,GuidelinesWaived
            ,DLReExam
            ,IsDocketed
            ,DocketSentencingChangesOnly
            ,CaseProcessActionID
            ,SentencingJudgeID
            ,Commitment
            ,FollowedBy
            ,JudicialWarning
            ,AlternativeCourtSanction
            ,NonJudicial
            ,ImpoundmentVIN
            ,ImpoundmentNoticeDate
            ,ImpoundmentPlateNumber
            ,ImpoundmentVehicleYear
            ,ImpoundmentVehicleMake
            ,ImpoundmentVehicleModel
            ,ImpoundmentVehicleColor
            ,ImpoundmentDays
            ,ImpoundmentOwnerID
            ,ImpoundmentLienHolderID
            ,VerdictDate
            ,IDISchool
            ,ChildRestraintSchool
            ,CreateByUserID
            ,CreateDate
            ,ModifyByUserID
            ,ModifyDate
            ,OBTSErrorMessages
            ,DispositionJudgeID
            ,SentencingSchoolHours
            ,DisposedByID
            ,BookingNumber
            ,RefNumber
            ,CommunityControlLengthCode
            ,ProbationStartDate
            ,ConfinementStartDate
            ,WaivedAttorney
            ,MandateDate
            ,AppealBondAmount
            ,AmendedBondAmount
            ,DirectFiling
            ,RestitutionAmountSentencing
            ,ComplaintNumber
            ,ChargePoints
            ,DLSuspensionStartDate
            ,DLSuspensionEndDate
            ,DLModifySuspensionStartDate
            ,DLModifySuspensionEndDate
            ,DLModificationCode
            ,CourtStatuteModifiedReason
            ,InitialEssentialFacts
            ,ProsecutorEssentialFacts
            ,CourtEssentialFacts
            ,InitialEssentialFactID
            ,ProsecutorEssentialFactID
            ,CourtEssentialFactID
            ,ProbationEndDate
FROM tblCaseCharge